---
- hosts: '{{target}}'
  tasks: 
    - name: install helloweb
      docker_container: 
        name: helloweb
        image: yvespelle/helloweb
        ports: 
          - 81:80
      when: (ansible_distribution == 'Ubuntu' or ansible_os_family == 'RedHat')
