---
- hosts: '{{target}}'
  tasks: 
    - name: LAMP installation Debian/Ubuntu
      apt: name={{item}} state=present
      with_items: '{{lamp_packages_deb}}'
      when: ansible_os_family == 'Debian'

    - name: LAMP installation Centos/RedHat
      yum: name={{item}} state=present
      with_items: '{{lamp_packages_el}}'
      when: ansible_os_family == 'RedHat'
      
    - name: redemarrer des services RedHat/CentOs
      shell: systemctl restart httpd mariadb && systemctl enable http mariadb
      when: ansible_os_family == 'RedHat'
    
    - name: redemarrer des services Debian/Ubuntu
      shell: systemctl restart apache2 mariadb && systemctl enable apache2 mariadb
      when: ansible_os_family == 'Debian'
      
    - name: ouverture du parefeu RedHat
      shell: firewall-cmd --zone=public --permanent --add-service=http && firewall-cmd --reload
      when: ansible_os_family == 'RedHat'



